SHARED_CSS = (
    ".grid {"
    "  display: grid;"
    "  grid-template-columns: repeat(auto-fill, minmax(155px, 1fr));"
    "  gap: 14px;"
    "  padding: 4px 16px 24px;"
    "}"
    ".enemy-grid {"
    "  display: grid;"
    "  grid-template-columns: repeat(auto-fill, minmax(190px, 1fr));"
    "  gap: 14px;"
    "  padding: 4px 16px 24px;"
    "}"
    ".enc-grid {"
    "  display: flex;"
    "  flex-wrap: wrap;"
    "  gap: 16px;"
    "  padding: 4px 16px 24px;"
    "  align-items: flex-start;"
    "}"
    ".card-tile, .enc-tile {"
    "  position: relative;"
    "  background: #1e1e2e;"
    "  border: 1px solid #333355;"
    "  border-radius: 12px;"
    "  overflow: visible;"
    "  cursor: default;"
    "  transition: transform 0.15s, box-shadow 0.15s;"
    "}"
    ".card-tile:hover, .enc-tile:hover {"
    "  transform: translateY(-4px);"
    "  box-shadow: 0 8px 24px rgba(0,0,0,0.5);"
    "}"
    ".card-img-wrap {"
    "  width: 100%;"
    "  aspect-ratio: 3/4;"
    "  border-radius: 10px 10px 0 0;"
    "  overflow: hidden;"
    "}"
    ".enemy-img-wrap {"
    "  width: 190px;"
    "  height: 226px;"
    "  border-radius: 10px 10px 0 0;"
    "  overflow: hidden;"
    "}"
    ".card-art {"
    "  width: 100%;"
    "  height: 100%;"
    "  object-fit: cover;"
    "  display: block;"
    "}"
    ".enemy-art {"
    "  object-fit: contain !important;"
    "  background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);"
    "  padding: 8px;"
    "}"
    ".card-art-placeholder {"
    "  width: 100%;"
    "  height: 100%;"
    "  background: linear-gradient(135deg, #2a2a4a 0%, #3a2060 100%);"
    "  display: flex;"
    "  align-items: center;"
    "  justify-content: center;"
    "  font-size: 28px;"
    "  font-weight: 700;"
    "  color: rgba(255,255,255,0.35);"
    "  letter-spacing: 1px;"
    "}"
    ".enc-tile {"
    "  width: fit-content;"
    "  min-width: 190px;"
    "  max-width: 700px;"
    "}"
    ".enc-portraits-row {"
    "  display: flex;"
    "  flex-direction: row;"
    "  align-items: flex-end;"
    "  justify-content: center;"
    "  gap: 12px;"
    "  padding: 16px 16px 0;"
    "  background: linear-gradient(160deg, #1a1a2e 0%, #0f1624 100%);"
    "  border-radius: 10px 10px 0 0;"
    "  min-height: 210px;"
    "}"
    ".enc-portrait-wrap {"
    "  display: flex;"
    "  flex-direction: column;"
    "  align-items: center;"
    "  gap: 5px;"
    "  flex: 0 0 auto;"
    "  width: 140px;"
    "}"
    ".enc-portrait-img-wrap {"
    "  position: relative;"
    "  width: 160px;"
    "  height: 200px;"
    "}"
    ".enc-portrait-img {"
    "  width: 100%;"
    "  height: 100%;"
    "  object-fit: contain;"
    "  display: block;"
    "  filter: drop-shadow(0 3px 8px rgba(0,0,0,0.7));"
    "}"
    ".enc-portrait-placeholder {"
    "  position: absolute;"
    "  inset: 0;"
    "  display: none;"
    "  align-items: center;"
    "  justify-content: center;"
    "  font-size: 22px;"
    "  font-weight: 700;"
    "  color: rgba(255,255,255,0.3);"
    "  background: #2a2a4a;"
    "  border-radius: 8px;"
    "}"
    ".portrait-count {"
    "  position: absolute;"
    "  top: -5px;"
    "  right: -5px;"
    "  background: #5b8dee;"
    "  color: #fff;"
    "  font-size: 10px;"
    "  font-weight: 700;"
    "  padding: 1px 5px;"
    "  border-radius: 8px;"
    "  border: 1px solid #1e1e2e;"
    "}"
    ".enc-portrait-name {"
    "  font-size: 13px;"
    "  color: #99aacc;"
    "  text-align: center;"
    "  white-space: nowrap;"
    "  overflow: hidden;"
    "  text-overflow: ellipsis;"
    "  width: 140px;"
    "  padding-bottom: 8px;"
    "}"
    ".card-body { padding: 8px 10px 11px; }"
    ".card-name {"
    "  font-size: 15px;"
    "  font-weight: 600;"
    "  color: #e0e0ff;"
    "  margin-bottom: 5px;"
    "  white-space: nowrap;"
    "  overflow: hidden;"
    "  text-overflow: ellipsis;"
    "}"
    ".enc-name {"
    "  white-space: normal !important;"
    "  overflow: visible !important;"
    "  text-overflow: unset !important;"
    "  line-height: 1.3;"
    "  margin-bottom: 6px;"
    "}"
    ".char-badge {"
    "  display: inline-block;"
    "  font-size: 12px;"
    "  font-weight: 600;"
    "  padding: 1px 6px;"
    "  border-radius: 4px;"
    "  margin-bottom: 7px;"
    "  letter-spacing: 0.3px;"
    "}"
    ".stat-row { display: flex; align-items: center; gap: 5px; margin-bottom: 4px; }"
    ".stat-label { font-size: 14px; color: #888; width: 28px; flex-shrink: 0; }"
    ".stat-label-enemy { font-size: 14px; color: #888; width: 70px; flex-shrink: 0; }"
    ".stat-val-plain { font-size: 12px; color: #ccc; }"
    ".bar-wrap { flex: 1; height: 5px; background: #2a2a3a; border-radius: 3px; overflow: hidden; }"
    ".bar-fill { height: 100%; border-radius: 3px; }"
    ".bar-blue { background: #5b8dee; }"
    ".stat-val { font-size: 12px; color: #ccc; width: 36px; text-align: right; flex-shrink: 0; }"
    ".section-header {"
    "  font-size: 16px;"
    "  font-weight: 700;"
    "  color: #c8c8ff;"
    "  padding: 14px 16px 6px;"
    "  letter-spacing: 0.4px;"
    "  border-bottom: 1px solid #2a2a4a;"
    "  margin-bottom: 4px;"
    "}"
    "#card-portal-tooltip {"
    "  display: none; position: fixed;"
    "  background: #12121f; border: 1px solid #444466;"
    "  border-radius: 10px; padding: 12px 14px;"
    "  min-width: 185px; max-width: 220px;"
    "  z-index: 99999; pointer-events: none;"
    "  box-shadow: 0 4px 20px rgba(0,0,0,0.7);"
    "}"
    "#card-portal-tooltip.visible { display: block; }"
    ".tt-title { font-size: 18px; font-weight: 700; color: #e0e0ff; margin-bottom: 3px; }"
    ".tt-desc { font-size: 15px; color: #8888aa; margin-bottom: 8px; border-bottom: 1px solid #2a2a4a; padding-bottom: 6px; }"
    ".tt-char { font-size: 15px; margin-bottom: 8px; border-bottom: 1px solid #2a2a4a; padding-bottom: 6px; }"
    ".tt-table { width: 100%; border-collapse: collapse; font-size: 14px; }"
    ".tt-table td { padding: 3px 0; color: #aaa; }"
    ".tt-table td:last-child { text-align: right; color: #ddd; }"
    ".relic-img-wrap {"
    "  width: 100%;"
    "  height: 110px;"
    "  border-radius: 10px 10px 0 0;"
    "  overflow: hidden;"
    "  background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);"
    "  display: flex;"
    "  align-items: center;"
    "  justify-content: center;"
    "}"
    ".relic-art {"
    "  max-width: 80px;"
    "  max-height: 80px;"
    "  object-fit: contain;"
    "  filter: drop-shadow(0 2px 6px rgba(0,0,0,0.8));"
    "}"
    ".relic-placeholder {"
    "  width: 80px !important;"
    "  height: 80px !important;"
    "  border-radius: 50% !important;"
    "}"
)

TOOLTIP_JS = (
    "const tooltip = document.getElementById('card-portal-tooltip');"
    "const MARGIN = 10;"
    "document.querySelectorAll('.card-tile, .enc-tile').forEach(tile => {"
    "  tile.addEventListener('mouseenter', () => {"
    "    tooltip.innerHTML = tile.dataset.tooltip;"
    "    tooltip.classList.add('visible');"
    "    positionTooltip(tile);"
    "  });"
    "  tile.addEventListener('mouseleave', () => {"
    "    tooltip.classList.remove('visible');"
    "  });"
    "});"
    "document.querySelectorAll('.enc-portrait-img').forEach(img => {"
    "  img.addEventListener('error', function() {"
    "    this.style.display = 'none';"
    "    const ph = this.nextElementSibling;"
    "    if (ph) ph.style.display = 'flex';"
    "  });"
    "});"
    "function positionTooltip(tile) {"
    "  const rect = tile.getBoundingClientRect();"
    "  const tw = tooltip.offsetWidth || 200;"
    "  const th = tooltip.offsetHeight || 160;"
    "  const vw = window.innerWidth;"
    "  const vh = window.innerHeight;"
    "  let top = rect.top - th - 8;"
    "  if (top < MARGIN) top = rect.bottom + 8;"
    "  if (top + th > vh - MARGIN) top = vh - th - MARGIN;"
    "  let left = rect.left + rect.width / 2 - tw / 2;"
    "  left = Math.max(MARGIN, Math.min(left, vw - tw - MARGIN));"
    "  tooltip.style.top = top + 'px';"
    "  tooltip.style.left = left + 'px';"
    "}"
)