{
  "acts": [
    "ACT.UNDERDOCKS",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 7,
  "build_id": "v0.99.1",
  "game_mode": "standard",
  "killed_by_encounter": "NONE.NONE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "ARCANE_SCROLL",
                "title": {
                  "key": "ARCANE_SCROLL.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "STONE_HUMIDIFIER",
                "title": {
                  "key": "STONE_HUMIDIFIER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PRECARIOUS_SHEARS",
                "title": {
                  "key": "PRECARIOUS_SHEARS.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ADRENALINE"
              }
            ],
            "current_gold": 99,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ARCANE_SCROLL.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 56,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "relic_choices": [
              {
                "choice": "RELIC.ARCANE_SCROLL",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "NUTRITIOUS_OYSTER",
                "title": {
                  "key": "NUTRITIOUS_OYSTER.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "GOLDEN_PEARL",
                "title": {
                  "key": "GOLDEN_PEARL.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "SCROLL_BOXES",
                "title": {
                  "key": "SCROLL_BOXES.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 99,
            "current_hp": 71,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "NUTRITIOUS_OYSTER.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 71,
            "max_hp": 86,
            "max_hp_gained": 11,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "relic_choices": [
              {
                "choice": "RELIC.NUTRITIOUS_OYSTER",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.UP_MY_SLEEVE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PREPARED"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEADLY_POISON"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.UP_MY_SLEEVE"
              }
            ],
            "current_gold": 107,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.WROUGHT_IN_WAR"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CRESCENT_SPEAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.STARDUST"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 2,
                "id": "CARD.WROUGHT_IN_WAR"
              }
            ],
            "current_gold": 107,
            "current_hp": 63,
            "damage_taken": 8,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 86,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "potion_choices": [
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLUDGE_SPINNER_WEAK",
            "monster_ids": [
              "MONSTER.SLUDGE_SPINNER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 107,
            "current_hp": 42,
            "damage_taken": 14,
            "event_choices": [
              {
                "title": {
                  "key": "ROOM_FULL_OF_CHEESE.pages.INITIAL.options.SEARCH.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "relic_choices": [
              {
                "choice": "RELIC.CHOSEN_CHEESE",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 107,
            "current_hp": 49,
            "damage_taken": 14,
            "event_choices": [
              {
                "title": {
                  "key": "ROOM_FULL_OF_CHEESE.pages.INITIAL.options.SEARCH.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 86,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "relic_choices": [
              {
                "choice": "RELIC.CHOSEN_CHEESE",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.ROOM_FULL_OF_CHEESE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.STRANGLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAND_TRICK"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PIERCING_WAIL"
              }
            ],
            "current_gold": 115,
            "current_hp": 43,
            "damage_taken": 0,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 71,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "potion_choices": [
              {
                "choice": "POTION.BLESSING_OF_THE_FORGE",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.MANIFEST_AUTHORITY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BEGONE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PROPHESIZE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 4,
                "id": "CARD.MANIFEST_AUTHORITY"
              }
            ],
            "current_gold": 122,
            "current_hp": 50,
            "damage_taken": 0,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 87,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198121360293
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEAPUNK_WEAK",
            "monster_ids": [
              "MONSTER.SEAPUNK"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEADLY_POISON"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SPEEDSTER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HUDDLE_UP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.KNOCKDOWN"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DAGGER_THROW"
              },
              {
                "id": "CARD.ANTICIPATE"
              }
            ],
            "current_gold": 14,
            "current_hp": 43,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 101,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 71,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "potion_choices": [
              {
                "choice": "POTION.FAIRY_IN_A_BOTTLE",
                "was_picked": false
              },
              {
                "choice": "POTION.OROBIC_ACID",
                "was_picked": false
              },
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.LUCKY_FYSH",
                "was_picked": false
              },
              {
                "choice": "RELIC.AMETHYST_AUBERGINE",
                "was_picked": false
              },
              {
                "choice": "RELIC.LAVA_LAMP",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.CATASTROPHE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.GLITTERSTREAM"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 5,
                "id": "CARD.CATASTROPHE"
              },
              {
                "floor_added_to_deck": 5,
                "id": "CARD.GLITTERSTREAM"
              }
            ],
            "current_gold": 14,
            "current_hp": 50,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 108,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 87,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198121360293
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.HAND_TRICK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.UP_MY_SLEEVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MEMENTO_MORI"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.HAND_TRICK"
              }
            ],
            "current_gold": 42,
            "current_hp": 37,
            "damage_taken": 7,
            "gold_gained": 28,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 72,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "potion_choices": [
              {
                "choice": "POTION.FORTIFIER",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.BLESSING_OF_THE_FORGE"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BOWLER_HAT",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.PHOTON_CUT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PALE_BLUE_DOT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.KNOW_THY_PLACE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 6,
                "id": "CARD.PHOTON_CUT"
              }
            ],
            "current_gold": 45,
            "current_hp": 43,
            "damage_taken": 8,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 88,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "potion_choices": [
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.STRENGTH_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.RED_MASK",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TERROR_EEL_ELITE",
            "monster_ids": [
              "MONSTER.TERROR_EEL"
            ],
            "room_type": "elite",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 42,
            "current_hp": 37,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 72,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.NEUTRALIZE"
            ]
          },
          {
            "current_gold": 45,
            "current_hp": 43,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 88,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.CATASTROPHE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.GREED"
              }
            ],
            "current_gold": 470,
            "current_hp": 37,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SUNKEN_TREASURY.pages.INITIAL.options.SECOND_CHEST.title",
                  "table": "events"
                },
                "variables": {
                  "SmallChestGold": {
                    "type": "BaseDynamic",
                    "decimal_value": 56,
                    "bool_value": false,
                    "string_value": null
                  },
                  "LargeChestGold": {
                    "type": "BaseDynamic",
                    "decimal_value": 357,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 428,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 72,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692
          },
          {
            "cards_gained": [
              {
                "id": "CARD.GREED"
              }
            ],
            "current_gold": 371,
            "current_hp": 43,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SUNKEN_TREASURY.pages.INITIAL.options.SECOND_CHEST.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 326,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 88,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198121360293
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SUNKEN_TREASURY",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 512,
            "current_hp": 37,
            "damage_taken": 0,
            "gold_gained": 42,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 72,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "relic_choices": [
              {
                "choice": "RELIC.JUZU_BRACELET",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 406,
            "current_hp": 43,
            "damage_taken": 0,
            "gold_gained": 35,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 88,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "relic_choices": [
              {
                "choice": "RELIC.TUNING_FORK",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_colorless": [
              "CARD.IMPATIENCE"
            ],
            "bought_potions": [
              "POTION.WEAK_POTION"
            ],
            "bought_relics": [
              "RELIC.TINGSHA"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.BACKSTAB"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FLECHETTES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEADLY_POISON"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.INFINITE_BLADES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CALAMITY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PREPARED"
              },
              {
                "id": "CARD.IMPATIENCE"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              }
            ],
            "current_gold": 11,
            "current_hp": 37,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 501,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 72,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "potion_choices": [
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.TINGSHA",
                "was_picked": true
              },
              {
                "choice": "RELIC.UNSETTLING_LAMP",
                "was_picked": false
              },
              {
                "choice": "RELIC.CHEMICAL_X",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 10,
                  "id": "CARD.DISCOVERY"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 10,
                "id": "CARD.DISCOVERY"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_REGENT"
              }
            ],
            "current_gold": 23,
            "current_hp": 43,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 308,
            "gold_spent": 75,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 88,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "relic_choices": [
              {
                "choice": "RELIC.PERMAFROST",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 11,
            "current_hp": 37,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 72,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.PREPARED"
            ]
          },
          {
            "current_gold": 23,
            "current_hp": 43,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 88,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.DISCOVERY"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 12,
                  "id": "CARD.DODGE_AND_ROLL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.LEADING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CLOAK_AND_DAGGER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DODGE_AND_ROLL"
              }
            ],
            "current_gold": 25,
            "current_hp": 38,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 73,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "potion_choices": [
              {
                "choice": "POTION.SHACKLING_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.WEAK_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 12,
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PATTER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PALE_BLUE_DOT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 12,
                "id": "CARD.COSMIC_INDIFFERENCE"
              }
            ],
            "current_gold": 30,
            "current_hp": 44,
            "damage_taken": 0,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 89,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198121360293
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TOADPOLES_WEAK",
            "monster_ids": [
              "MONSTER.TOADPOLE",
              "MONSTER.TOADPOLE"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.BLADE_DANCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SUCKER_PUNCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SKEWER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BLADE_DANCE"
              }
            ],
            "current_gold": 37,
            "current_hp": 39,
            "damage_taken": 0,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 74,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198135971692
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.KINGLY_KICK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GLITTERSTREAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PATTER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 13,
                "id": "CARD.KINGLY_KICK"
              }
            ],
            "current_gold": 40,
            "current_hp": 35,
            "damage_taken": 10,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 90,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198121360293
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.HAUNTED_SHIP_NORMAL",
            "monster_ids": [
              "MONSTER.HAUNTED_SHIP"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SNAKEBITE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MIRAGE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 45,
            "current_hp": 13,
            "damage_taken": 27,
            "event_choices": [
              {
                "title": {
                  "key": "PUNCH_OFF.pages.INITIAL.options.I_CAN_TAKE_THEM.title",
                  "table": "events"
                },
                "variables": {}
              },
              {
                "title": {
                  "key": "PUNCH_OFF.pages.I_CAN_TAKE_THEM.options.FIGHT.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 75,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "potion_choices": [
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.SHACKLING_POTION",
              "POTION.FORTIFIER"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.MINIATURE_CANNON",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.SOLAR_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COLLISION_COURSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GLITTERSTREAM"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 14,
                "id": "CARD.SOLAR_STRIKE"
              }
            ],
            "current_gold": 47,
            "current_hp": 25,
            "damage_taken": 11,
            "event_choices": [
              {
                "title": {
                  "key": "PUNCH_OFF.pages.INITIAL.options.I_CAN_TAKE_THEM.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "PUNCH_OFF.pages.I_CAN_TAKE_THEM.options.FIGHT.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 91,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "potion_choices": [
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.DEXTERITY_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.KUSARIGAMA",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.PUNCH_OFF",
            "room_type": "event",
            "turns_taken": 0
          },
          {
            "model_id": "ENCOUNTER.PUNCH_OFF_EVENT_ENCOUNTER",
            "monster_ids": [
              "MONSTER.PUNCH_CONSTRUCT",
              "MONSTER.PUNCH_CONSTRUCT"
            ],
            "room_type": "monster",
            "turns_taken": 9
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 45,
            "current_hp": 35,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 22,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 47,
            "current_hp": 52,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 27,
            "max_hp": 91,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 16,
                  "id": "CARD.AFTERIMAGE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GRAND_FINALE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NIGHTMARE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.AFTERIMAGE"
              }
            ],
            "current_gold": 135,
            "current_hp": 2,
            "damage_taken": 35,
            "gold_gained": 90,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 76,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "potion_used": [
              "POTION.POWER_POTION",
              "POTION.ATTACK_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 16,
                  "id": "CARD.MONARCHS_GAZE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.NEUTRON_AEGIS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HEAVENLY_DRILL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 16,
                "id": "CARD.MONARCHS_GAZE"
              }
            ],
            "current_gold": 122,
            "current_hp": 37,
            "damage_taken": 16,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 92,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "potion_choices": [
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.WATERFALL_GIANT_BOSS",
            "monster_ids": [
              "MONSTER.WATERFALL_GIANT"
            ],
            "room_type": "boss",
            "turns_taken": 11
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "YUMMY_COOKIE",
                "title": {
                  "key": "YUMMY_COOKIE.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "BIIIG_HUG",
                "title": {
                  "key": "BIIIG_HUG.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "GOLDEN_COMPASS",
                "title": {
                  "key": "GOLDEN_COMPASS.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 135,
            "current_hp": 61,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "YUMMY_COOKIE.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 59,
            "max_hp": 76,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "relic_choices": [
              {
                "choice": "RELIC.YUMMY_COOKIE",
                "was_picked": true
              }
            ],
            "upgraded_cards": [
              "CARD.AFTERIMAGE",
              "CARD.ADRENALINE",
              "CARD.UP_MY_SLEEVE",
              "CARD.IMPATIENCE"
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "VERY_HOT_COCOA",
                "title": {
                  "key": "VERY_HOT_COCOA.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "SEAL_OF_GOLD",
                "title": {
                  "key": "SEAL_OF_GOLD.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PUMPKIN_CANDLE",
                "title": {
                  "key": "PUMPKIN_CANDLE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 122,
            "current_hp": 81,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "VERY_HOT_COCOA.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 44,
            "max_hp": 92,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "relic_choices": [
              {
                "choice": "RELIC.VERY_HOT_COCOA",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TEZCATARA",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 18,
                  "id": "CARD.POUNCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DEFLECT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DODGE_AND_ROLL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 6,
                "id": "CARD.HAND_TRICK"
              },
              {
                "id": "CARD.POUNCE"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 6,
                "id": "CARD.HAND_TRICK"
              }
            ],
            "current_gold": 147,
            "current_hp": 55,
            "damage_taken": 7,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 77,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "potion_choices": [
              {
                "choice": "POTION.GHOST_IN_A_JAR",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 18,
                  "id": "CARD.BEGONE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PARRY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.REFINE_BLADE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.KINGLY_KICK"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 18,
                "id": "CARD.BEGONE"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 13,
                "id": "CARD.KINGLY_KICK"
              }
            ],
            "current_gold": 136,
            "current_hp": 79,
            "damage_taken": 3,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 93,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198121360293
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THIEVING_HOPPER_WEAK",
            "monster_ids": [
              "MONSTER.THIEVING_HOPPER"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 19,
                  "id": "CARD.PROWESS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.VOLLEY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.THRUMMING_HATCHET"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PROWESS"
              }
            ],
            "current_gold": 147,
            "current_hp": 50,
            "damage_taken": 5,
            "event_choices": [
              {
                "title": {
                  "key": "BRAIN_LEECH.pages.INITIAL.options.RIP.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 77,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 19,
                  "id": "CARD.JACK_OF_ALL_TRADES"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.AUTOMATION"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PANACHE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 19,
                "id": "CARD.JACK_OF_ALL_TRADES"
              }
            ],
            "current_gold": 136,
            "current_hp": 74,
            "damage_taken": 5,
            "event_choices": [
              {
                "title": {
                  "key": "BRAIN_LEECH.pages.INITIAL.options.RIP.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 93,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198121360293
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.BRAIN_LEECH",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.ANTICIPATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DASH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.UP_MY_SLEEVE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 157,
            "current_hp": 49,
            "damage_taken": 2,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 78,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198135971692
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 20,
                  "id": "CARD.HIDDEN_CACHE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PATTER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CHILD_OF_THE_STARS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 20,
                "id": "CARD.HIDDEN_CACHE"
              }
            ],
            "current_gold": 148,
            "current_hp": 74,
            "damage_taken": 1,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 94,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "potion_used": [
              "POTION.SWIFT_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TUNNELER_WEAK",
            "monster_ids": [
              "MONSTER.TUNNELER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.LEADING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MEMENTO_MORI"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SNAKEBITE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.OUTBREAK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PROWESS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NOSTALGIA"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ACROBATICS"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              }
            ],
            "current_gold": 7,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 150,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 78,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "potion_choices": [
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.STABLE_SERUM",
                "was_picked": false
              },
              {
                "choice": "POTION.LIQUID_BRONZE",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.VEXING_PUZZLEBOX",
                "was_picked": false
              },
              {
                "choice": "RELIC.PAPER_KRANE",
                "was_picked": false
              },
              {
                "choice": "RELIC.BREAD",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 21,
                  "id": "CARD.LARGESSE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "floor_added_to_deck": 21,
                  "id": "CARD.CHARGE"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 21,
                "id": "CARD.LARGESSE"
              },
              {
                "floor_added_to_deck": 21,
                "id": "CARD.CHARGE"
              }
            ],
            "current_gold": 1,
            "current_hp": 74,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 147,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 94,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198121360293
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 7,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 78,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.PROWESS"
            ]
          },
          {
            "current_gold": 1,
            "current_hp": 74,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 94,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.JACK_OF_ALL_TRADES"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 23,
                  "id": "CARD.HIDDEN_DAGGERS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BACKFLIP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.HIDDEN_DAGGERS"
              }
            ],
            "current_gold": 22,
            "current_hp": 47,
            "damage_taken": 3,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 79,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198135971692
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 23,
                  "id": "CARD.SHINING_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CELESTIAL_MIGHT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 23,
                "id": "CARD.SHINING_STRIKE"
              }
            ],
            "current_gold": 13,
            "current_hp": 58,
            "damage_taken": 17,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 95,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "potion_choices": [
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.SPEED_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.MYTES_NORMAL",
            "monster_ids": [
              "MONSTER.MYTE",
              "MONSTER.MYTE"
            ],
            "room_type": "monster",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 61,
            "current_hp": 47,
            "damage_taken": 0,
            "gold_gained": 39,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 79,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "relic_choices": [
              {
                "choice": "RELIC.MERCURY_HOURGLASS",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 49,
            "current_hp": 58,
            "damage_taken": 0,
            "gold_gained": 36,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 95,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "relic_choices": [
              {
                "choice": "RELIC.REPTILE_TRINKET",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_enchanted": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.PERFECT_FIT"
                  },
                  "floor_added_to_deck": 10,
                  "id": "CARD.PREPARED"
                },
                "enchantment": "ENCHANTMENT.PERFECT_FIT"
              }
            ],
            "current_gold": 61,
            "current_hp": 47,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "FIELD_OF_MAN_SIZED_HOLES.pages.INITIAL.options.ENTER_YOUR_HOLE.title",
                  "table": "events"
                },
                "variables": {
                  "ResistCurse": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Normality"
                  },
                  "Enchantment": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Perfect Fit"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 79,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692
          },
          {
            "cards_enchanted": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.PERFECT_FIT"
                  },
                  "floor_added_to_deck": 5,
                  "id": "CARD.CATASTROPHE"
                },
                "enchantment": "ENCHANTMENT.PERFECT_FIT"
              }
            ],
            "current_gold": 49,
            "current_hp": 58,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "FIELD_OF_MAN_SIZED_HOLES.pages.INITIAL.options.ENTER_YOUR_HOLE.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 95,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198121360293
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.FIELD_OF_MAN_SIZED_HOLES",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 26,
                  "id": "CARD.PHANTOM_BLADES"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.POISONED_STAB"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.UNTOUCHABLE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PHANTOM_BLADES"
              }
            ],
            "current_gold": 99,
            "current_hp": 48,
            "damage_taken": 0,
            "gold_gained": 38,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 80,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "potion_choices": [
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.TOUGH_BANDAGES",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 26,
                  "id": "CARD.VOID_FORM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SPECTRUM_SHIFT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SUMMON_FORTH"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 26,
                "id": "CARD.VOID_FORM"
              }
            ],
            "current_gold": 81,
            "current_hp": 48,
            "damage_taken": 11,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 96,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "potion_choices": [
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.SKILL_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.MINIATURE_CANNON",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.INFESTED_PRISMS_ELITE",
            "monster_ids": [
              "MONSTER.INFESTED_PRISM"
            ],
            "room_type": "elite",
            "turns_taken": 8
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 99,
            "current_hp": 48,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.HIDDEN_DAGGERS"
            ]
          },
          {
            "current_gold": 81,
            "current_hp": 48,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 96,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.VOID_FORM"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.SQUASH"
              }
            ],
            "current_gold": 99,
            "current_hp": 48,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "BUGSLAYER.pages.INITIAL.options.SQUASH.title",
                  "table": "events"
                },
                "variables": {
                  "Card1": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Exterminate"
                  },
                  "Card2": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Squash"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692
          },
          {
            "cards_gained": [
              {
                "id": "CARD.SQUASH"
              }
            ],
            "current_gold": 81,
            "current_hp": 48,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "BUGSLAYER.pages.INITIAL.options.SQUASH.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 96,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198121360293
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.BUGSLAYER",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 173,
            "current_hp": 48,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "LOST_WISP.pages.INITIAL.options.SEARCH.title",
                  "table": "events"
                },
                "variables": {
                  "Relic": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Lost Wisp"
                  },
                  "Curse": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Decay"
                  }
                }
              }
            ],
            "gold_gained": 74,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692
          },
          {
            "current_gold": 134,
            "current_hp": 48,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "LOST_WISP.pages.INITIAL.options.SEARCH.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 53,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 96,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198121360293
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.LOST_WISP",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 173,
            "current_hp": 48,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.ANTICIPATE"
            ]
          },
          {
            "current_gold": 134,
            "current_hp": 76,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 28,
            "max_hp": 96,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 31,
                  "id": "CARD.FAN_OF_KNIVES"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BULLET_TIME"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SNEAKY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.FAN_OF_KNIVES"
              }
            ],
            "current_gold": 263,
            "current_hp": 38,
            "damage_taken": 11,
            "gold_gained": 90,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 81,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "potion_choices": [
              {
                "choice": "POTION.HEART_OF_IRON",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.POWER_POTION"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 31,
                  "id": "CARD.FOREGONE_CONCLUSION"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.TYRANNY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MONARCHS_GAZE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 31,
                "id": "CARD.FOREGONE_CONCLUSION"
              }
            ],
            "current_gold": 209,
            "current_hp": 36,
            "damage_taken": 41,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 97,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "potion_used": [
              "POTION.DEXTERITY_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.KAISER_CRAB_BOSS",
            "monster_ids": [
              "MONSTER.CRUSHER",
              "MONSTER.ROCKET"
            ],
            "room_type": "boss",
            "turns_taken": 9
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "TRI_BOOMERANG",
                "title": {
                  "key": "TRI_BOOMERANG.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "TANXS_WHISTLE",
                "title": {
                  "key": "TANXS_WHISTLE.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "SPIKED_GAUNTLETS",
                "title": {
                  "key": "SPIKED_GAUNTLETS.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.INSTINCT"
                  },
                  "floor_added_to_deck": 5,
                  "id": "CARD.DAGGER_THROW"
                },
                "enchantment": "ENCHANTMENT.INSTINCT"
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.INSTINCT"
                  },
                  "floor_added_to_deck": 18,
                  "id": "CARD.POUNCE"
                },
                "enchantment": "ENCHANTMENT.INSTINCT"
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.INSTINCT"
                  },
                  "floor_added_to_deck": 28,
                  "id": "CARD.SQUASH"
                },
                "enchantment": "ENCHANTMENT.INSTINCT"
              }
            ],
            "current_gold": 263,
            "current_hp": 72,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TRI_BOOMERANG.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 34,
            "max_hp": 81,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "relic_choices": [
              {
                "choice": "RELIC.TRI_BOOMERANG",
                "was_picked": true
              }
            ]
          },
          {
            "ancient_choice": [
              {
                "TextKey": "THROWING_AXE",
                "title": {
                  "key": "THROWING_AXE.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "WAR_HAMMER",
                "title": {
                  "key": "WAR_HAMMER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "TRI_BOOMERANG",
                "title": {
                  "key": "TRI_BOOMERANG.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.INSTINCT"
                  },
                  "floor_added_to_deck": 28,
                  "id": "CARD.SQUASH"
                },
                "enchantment": "ENCHANTMENT.INSTINCT"
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.INSTINCT"
                  },
                  "floor_added_to_deck": 6,
                  "id": "CARD.PHOTON_CUT"
                },
                "enchantment": "ENCHANTMENT.INSTINCT"
              },
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.INSTINCT"
                  },
                  "floor_added_to_deck": 23,
                  "id": "CARD.SHINING_STRIKE"
                },
                "enchantment": "ENCHANTMENT.INSTINCT"
              }
            ],
            "current_gold": 209,
            "current_hp": 84,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "TRI_BOOMERANG.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 48,
            "max_hp": 97,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "relic_choices": [
              {
                "choice": "RELIC.TRI_BOOMERANG",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TANX",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 33,
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.NOXIOUS_FUMES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FOLLOW_THROUGH"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PIERCING_WAIL"
              }
            ],
            "current_gold": 272,
            "current_hp": 73,
            "damage_taken": 0,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 82,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "potion_used": [
              "POTION.HEART_OF_IRON"
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 33,
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.KINGLY_PUNCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CRESCENT_SPEAR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 33,
                "id": "CARD.COSMIC_INDIFFERENCE"
              }
            ],
            "current_gold": 222,
            "current_hp": 78,
            "damage_taken": 7,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 98,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198121360293
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DEVOTED_SCULPTOR_WEAK",
            "monster_ids": [
              "MONSTER.DEVOTED_SCULPTOR"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_transformed": [
              {
                "final_card": {
                  "floor_added_to_deck": 34,
                  "id": "CARD.ADRENALINE"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_SILENT"
                }
              }
            ],
            "current_gold": 272,
            "current_hp": 73,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SYMBIOTE.pages.INITIAL.options.KILL_WITH_FIRE.title",
                  "table": "events"
                },
                "variables": {
                  "Enchantment": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Corrupted"
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692
          },
          {
            "cards_transformed": [
              {
                "final_card": {
                  "floor_added_to_deck": 34,
                  "id": "CARD.GATHER_LIGHT"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_REGENT"
                }
              }
            ],
            "current_gold": 222,
            "current_hp": 78,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SYMBIOTE.pages.INITIAL.options.KILL_WITH_FIRE.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 98,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198121360293
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SYMBIOTE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MEMENTO_MORI"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ESCAPE_PLAN"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SPEEDSTER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.VOLLEY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MASTER_OF_STRATEGY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BLUR"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              }
            ],
            "current_gold": 75,
            "current_hp": 73,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 197,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "potion_choices": [
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.LUCKY_TONIC",
                "was_picked": false
              },
              {
                "choice": "POTION.HEART_OF_IRON",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BAG_OF_PREPARATION",
                "was_picked": false
              },
              {
                "choice": "RELIC.HAPPY_FLOWER",
                "was_picked": false
              },
              {
                "choice": "RELIC.ORRERY",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 35,
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 35,
                "id": "CARD.COSMIC_INDIFFERENCE"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_REGENT"
              }
            ],
            "current_gold": 74,
            "current_hp": 78,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 48,
            "gold_spent": 100,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 98,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198121360293
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 149,
            "current_hp": 67,
            "damage_taken": 6,
            "event_choices": [
              {
                "title": {
                  "key": "THIS_OR_THAT.pages.INITIAL.options.PLAIN.title",
                  "table": "events"
                },
                "variables": {
                  "Curse": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Clumsy"
                  }
                }
              }
            ],
            "gold_gained": 74,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692
          },
          {
            "current_gold": 116,
            "current_hp": 72,
            "damage_taken": 6,
            "event_choices": [
              {
                "title": {
                  "key": "THIS_OR_THAT.pages.INITIAL.options.PLAIN.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 42,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 98,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198121360293
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.THIS_OR_THAT",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 149,
            "current_hp": 67,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.POUNCE"
            ]
          },
          {
            "current_gold": 116,
            "current_hp": 72,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 98,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.PHOTON_CUT"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 195,
            "current_hp": 67,
            "damage_taken": 0,
            "gold_gained": 46,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "relic_choices": [
              {
                "choice": "RELIC.AKABEKO",
                "was_picked": true
              }
            ]
          },
          {
            "current_gold": 154,
            "current_hp": 79,
            "damage_taken": 0,
            "gold_gained": 38,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 7,
            "max_hp": 105,
            "max_hp_gained": 7,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "relic_choices": [
              {
                "choice": "RELIC.STRAWBERRY",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 39,
                  "id": "CARD.BACKFLIP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEADLY_POISON"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BACKFLIP"
              }
            ],
            "current_gold": 228,
            "current_hp": 68,
            "damage_taken": 0,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 83,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "potion_choices": [
              {
                "choice": "POTION.TOUCH_OF_INSANITY",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.INTIMIDATING_HELMET",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 39,
                  "id": "CARD.PHOTON_CUT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.HIDDEN_CACHE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GUIDING_STAR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 39,
                "id": "CARD.PHOTON_CUT"
              }
            ],
            "current_gold": 181,
            "current_hp": 70,
            "damage_taken": 10,
            "gold_gained": 27,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 106,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "potion_choices": [
              {
                "choice": "POTION.DUPLICATOR",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BELLOWS",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.KNIGHTS_ELITE",
            "monster_ids": [
              "MONSTER.FLAIL_KNIGHT",
              "MONSTER.SPECTRAL_KNIGHT",
              "MONSTER.MAGI_KNIGHT"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 228,
            "current_hp": 68,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 83,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.ACROBATICS"
            ]
          },
          {
            "current_gold": 181,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 106,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.FOREGONE_CONCLUSION"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.POUNCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.LEADING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SNAKEBITE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 259,
            "current_hp": 62,
            "damage_taken": 7,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 84,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "potion_used": [
              "POTION.TOUCH_OF_INSANITY"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.GORGET",
                "was_picked": true
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CRUSH_UNDER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GATHER_LIGHT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ASTRAL_PULSE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 212,
            "current_hp": 53,
            "damage_taken": 18,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 107,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "potion_choices": [
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.DUPLICATOR"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.HAPPY_FLOWER",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.MECHA_KNIGHT_ELITE",
            "monster_ids": [
              "MONSTER.MECHA_KNIGHT"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 42,
                  "id": "CARD.CALCULATED_GAMBLE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.HAZE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.LEADING_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.CALCULATED_GAMBLE"
              }
            ],
            "current_gold": 273,
            "current_hp": 63,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 85,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198135971692
          },
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 42,
                  "id": "CARD.LARGESSE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PATTER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COSMIC_INDIFFERENCE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "floor_added_to_deck": 42,
                "id": "CARD.LARGESSE"
              }
            ],
            "current_gold": 219,
            "current_hp": 54,
            "damage_taken": 0,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 108,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "potion_used": [
              "POTION.EXPLOSIVE_AMPOULE"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SCROLLS_OF_BITING_WEAK",
            "monster_ids": [
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING",
              "MONSTER.SCROLL_OF_BITING"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_potions": [
              "POTION.DEXTERITY_POTION"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SUCKER_PUNCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEFLECT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLADE_DANCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ULTIMATE_DEFEND"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RALLY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ACCURACY"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              }
            ],
            "current_gold": 2,
            "current_hp": 63,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 271,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "potion_choices": [
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.POTION_OF_BINDING",
                "was_picked": false
              },
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.VAJRA",
                "was_picked": false
              },
              {
                "choice": "RELIC.PEAR",
                "was_picked": false
              },
              {
                "choice": "RELIC.BELT_BUCKLE",
                "was_picked": false
              }
            ]
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 43,
                  "id": "CARD.PALE_BLUE_DOT"
                },
                "was_picked": true
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 43,
                "id": "CARD.PALE_BLUE_DOT"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEFEND_REGENT"
              }
            ],
            "current_gold": 19,
            "current_hp": 54,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 75,
            "gold_spent": 125,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 108,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198121360293
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 2,
            "current_hp": 85,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 22,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "rest_site_choices": [
              "HEAL"
            ]
          },
          {
            "current_gold": 19,
            "current_hp": 86,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 32,
            "max_hp": 108,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 76561198121360293,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 2,
            "current_hp": 86,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 86,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198135971692,
            "potion_used": [
              "POTION.DEXTERITY_POTION"
            ]
          },
          {
            "current_gold": 19,
            "current_hp": 31,
            "damage_taken": 56,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 109,
            "max_hp_gained": 1,
            "max_hp_lost": 0,
            "player_id": 76561198121360293
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DOORMAKER_BOSS",
            "monster_ids": [
              "MONSTER.DOOR"
            ],
            "room_type": "boss",
            "turns_taken": 14
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "character": "CHARACTER.SILENT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.NEUTRALIZE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.SURVIVOR"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.ADRENALINE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 2,
          "id": "CARD.UP_MY_SLEEVE"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.PIERCING_WAIL"
        },
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.INSTINCT"
          },
          "floor_added_to_deck": 5,
          "id": "CARD.DAGGER_THROW"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 5,
          "id": "CARD.ANTICIPATE"
        },
        {
          "floor_added_to_deck": 8,
          "id": "CARD.GREED"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.PERFECT_FIT"
          },
          "floor_added_to_deck": 10,
          "id": "CARD.PREPARED"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 10,
          "id": "CARD.IMPATIENCE"
        },
        {
          "floor_added_to_deck": 12,
          "id": "CARD.DODGE_AND_ROLL"
        },
        {
          "floor_added_to_deck": 13,
          "id": "CARD.BLADE_DANCE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 16,
          "id": "CARD.AFTERIMAGE"
        },
        {
          "floor_added_to_deck": 18,
          "id": "CARD.HAND_TRICK"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.INSTINCT"
          },
          "floor_added_to_deck": 18,
          "id": "CARD.POUNCE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 19,
          "id": "CARD.PROWESS"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 21,
          "id": "CARD.ACROBATICS"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 23,
          "id": "CARD.HIDDEN_DAGGERS"
        },
        {
          "floor_added_to_deck": 26,
          "id": "CARD.PHANTOM_BLADES"
        },
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.INSTINCT"
          },
          "floor_added_to_deck": 28,
          "id": "CARD.SQUASH"
        },
        {
          "floor_added_to_deck": 31,
          "id": "CARD.FAN_OF_KNIVES"
        },
        {
          "floor_added_to_deck": 33,
          "id": "CARD.PIERCING_WAIL"
        },
        {
          "floor_added_to_deck": 34,
          "id": "CARD.ADRENALINE"
        },
        {
          "floor_added_to_deck": 35,
          "id": "CARD.BLUR"
        },
        {
          "floor_added_to_deck": 39,
          "id": "CARD.BACKFLIP"
        },
        {
          "floor_added_to_deck": 42,
          "id": "CARD.CALCULATED_GAMBLE"
        },
        {
          "floor_added_to_deck": 43,
          "id": "CARD.ACCURACY"
        }
      ],
      "id": 76561198135971692,
      "max_potion_slot_count": 2,
      "potions": [
        {
          "id": "POTION.GHOST_IN_A_JAR",
          "slot_index": 0
        }
      ],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.RING_OF_THE_SNAKE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.ARCANE_SCROLL"
        },
        {
          "floor_added_to_deck": 3,
          "id": "RELIC.CHOSEN_CHEESE"
        },
        {
          "floor_added_to_deck": 6,
          "id": "RELIC.BOWLER_HAT"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.JUZU_BRACELET"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.TINGSHA"
        },
        {
          "floor_added_to_deck": 14,
          "id": "RELIC.MINIATURE_CANNON"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.YUMMY_COOKIE"
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.MERCURY_HOURGLASS"
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.TOUGH_BANDAGES"
        },
        {
          "floor_added_to_deck": 32,
          "id": "RELIC.TRI_BOOMERANG"
        },
        {
          "floor_added_to_deck": 38,
          "id": "RELIC.AKABEKO"
        },
        {
          "floor_added_to_deck": 39,
          "id": "RELIC.INTIMIDATING_HELMET"
        },
        {
          "floor_added_to_deck": 41,
          "id": "RELIC.GORGET"
        }
      ]
    },
    {
      "character": "CHARACTER.REGENT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_REGENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.FALLING_STAR"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.VENERATE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.WROUGHT_IN_WAR"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.MANIFEST_AUTHORITY"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.PERFECT_FIT"
          },
          "floor_added_to_deck": 5,
          "id": "CARD.CATASTROPHE"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.GLITTERSTREAM"
        },
        {
          "current_upgrade_level": 1,
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.INSTINCT"
          },
          "floor_added_to_deck": 6,
          "id": "CARD.PHOTON_CUT"
        },
        {
          "floor_added_to_deck": 8,
          "id": "CARD.GREED"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 10,
          "id": "CARD.DISCOVERY"
        },
        {
          "floor_added_to_deck": 12,
          "id": "CARD.COSMIC_INDIFFERENCE"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.SOLAR_STRIKE"
        },
        {
          "floor_added_to_deck": 16,
          "id": "CARD.MONARCHS_GAZE"
        },
        {
          "floor_added_to_deck": 18,
          "id": "CARD.BEGONE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 19,
          "id": "CARD.JACK_OF_ALL_TRADES"
        },
        {
          "floor_added_to_deck": 20,
          "id": "CARD.HIDDEN_CACHE"
        },
        {
          "floor_added_to_deck": 21,
          "id": "CARD.LARGESSE"
        },
        {
          "floor_added_to_deck": 21,
          "id": "CARD.CHARGE"
        },
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.INSTINCT"
          },
          "floor_added_to_deck": 23,
          "id": "CARD.SHINING_STRIKE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 26,
          "id": "CARD.VOID_FORM"
        },
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.INSTINCT"
          },
          "floor_added_to_deck": 28,
          "id": "CARD.SQUASH"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 31,
          "id": "CARD.FOREGONE_CONCLUSION"
        },
        {
          "floor_added_to_deck": 33,
          "id": "CARD.COSMIC_INDIFFERENCE"
        },
        {
          "floor_added_to_deck": 34,
          "id": "CARD.GATHER_LIGHT"
        },
        {
          "floor_added_to_deck": 35,
          "id": "CARD.COSMIC_INDIFFERENCE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 39,
          "id": "CARD.PHOTON_CUT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 42,
          "id": "CARD.LARGESSE"
        },
        {
          "floor_added_to_deck": 43,
          "id": "CARD.PALE_BLUE_DOT"
        }
      ],
      "id": 76561198121360293,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.DIVINE_RIGHT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.NUTRITIOUS_OYSTER"
        },
        {
          "floor_added_to_deck": 3,
          "id": "RELIC.CHOSEN_CHEESE"
        },
        {
          "floor_added_to_deck": 6,
          "id": "RELIC.RED_MASK"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.TUNING_FORK",
          "props": {
            "ints": [
              {
                "name": "SkillsPlayed",
                "value": 7
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.PERMAFROST"
        },
        {
          "floor_added_to_deck": 14,
          "id": "RELIC.KUSARIGAMA"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.VERY_HOT_COCOA"
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.REPTILE_TRINKET"
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.MINIATURE_CANNON"
        },
        {
          "floor_added_to_deck": 32,
          "id": "RELIC.TRI_BOOMERANG"
        },
        {
          "floor_added_to_deck": 38,
          "id": "RELIC.STRAWBERRY"
        },
        {
          "floor_added_to_deck": 39,
          "id": "RELIC.BELLOWS"
        },
        {
          "floor_added_to_deck": 41,
          "id": "RELIC.HAPPY_FLOWER",
          "props": {
            "ints": [
              {
                "name": "TurnsSeen",
                "value": 2
              }
            ]
          }
        }
      ]
    }
  ],
  "run_time": 3856,
  "schema_version": 8,
  "seed": "S57R5E8NB2",
  "start_time": 1775800521,
  "was_abandoned": false,
  "win": true
}