{
  "acts": [
    "ACT.OVERGROWTH",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 10,
  "build_id": "v0.103.2",
  "game_mode": "standard",
  "killed_by_encounter": "ENCOUNTER.DECIMILLIPEDE_ELITE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "GOLDEN_PEARL",
                "title": {
                  "key": "GOLDEN_PEARL.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "WINGED_BOOTS",
                "title": {
                  "key": "WINGED_BOOTS.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "SCROLL_BOXES",
                "title": {
                  "key": "SCROLL_BOXES.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.LEADING_STRIKE"
              },
              {
                "id": "CARD.ANTICIPATE"
              },
              {
                "id": "CARD.SKEWER"
              }
            ],
            "current_gold": 0,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SCROLL_BOXES.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 99,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 56,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.SCROLL_BOXES",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.ACROBATICS"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BUBBLE_BUBBLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ACROBATICS"
              }
            ],
            "current_gold": 13,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FUZZY_WURM_CRAWLER_WEAK",
            "monster_ids": [
              "MONSTER.FUZZY_WURM_CRAWLER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.FOLLOW_THROUGH"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.POISONED_STAB"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEADLY_POISON"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.FOLLOW_THROUGH"
              }
            ],
            "current_gold": 28,
            "current_hp": 52,
            "damage_taken": 4,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLIMES_WEAK",
            "monster_ids": [
              "MONSTER.LEAF_SLIME_S",
              "MONSTER.LEAF_SLIME_M",
              "MONSTER.TWIG_SLIME_S"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.DEFLECT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.POISONED_STAB"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FOLLOW_THROUGH"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DEFLECT"
              }
            ],
            "current_gold": 36,
            "current_hp": 49,
            "damage_taken": 3,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SHRINKER_BEETLE_WEAK",
            "monster_ids": [
              "MONSTER.SHRINKER_BEETLE"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.UNTOUCHABLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LEADING_STRIKE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 50,
            "current_hp": 32,
            "damage_taken": 17,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SNAPPING_JAXFRUIT_NORMAL",
            "monster_ids": [
              "MONSTER.SNAPPING_JAXFRUIT",
              "MONSTER.FLYCONID"
            ],
            "room_type": "monster",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.PREPARED"
              },
              {
                "id": "CARD.FLICK_FLACK"
              }
            ],
            "current_gold": 50,
            "current_hp": 32,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ROOM_FULL_OF_CHEESE.pages.INITIAL.options.GORGE.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.ROOM_FULL_OF_CHEESE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 97,
            "current_hp": 32,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "JUNGLE_MAZE_ADVENTURE.pages.INITIAL.options.JOIN_FORCES.title",
                  "table": "events"
                },
                "variables": {
                  "SoloGold": {
                    "type": "BaseDynamic",
                    "decimal_value": 141.964318,
                    "bool_value": false,
                    "string_value": null
                  },
                  "JoinForcesGold": {
                    "type": "BaseDynamic",
                    "decimal_value": 47.32541,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 47,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.JUNGLE_MAZE_ADVENTURE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 97,
            "current_hp": 32,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.SKEWER"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 9,
                  "id": "CARD.PINPOINT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SUCKER_PUNCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PINPOINT"
              }
            ],
            "current_gold": 130,
            "current_hp": 19,
            "damage_taken": 13,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POISON_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.POWER_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BRONZE_SCALES",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PHROG_PARASITE_ELITE",
            "monster_ids": [
              "MONSTER.PHROG_PARASITE"
            ],
            "room_type": "elite",
            "turns_taken": 8
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 164,
            "current_hp": 19,
            "damage_taken": 0,
            "gold_gained": 34,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.TOXIC_EGG",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 164,
            "current_hp": 40,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 21,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 12,
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FLECHETTES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FLICK_FLACK"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.PIERCING_WAIL"
              }
            ],
            "current_gold": 171,
            "current_hp": 40,
            "damage_taken": 0,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLIMES_NORMAL",
            "monster_ids": [
              "MONSTER.TWIG_SLIME_M",
              "MONSTER.LEAF_SLIME_M",
              "MONSTER.LEAF_SLIME_S",
              "MONSTER.TWIG_SLIME_S"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 171,
            "current_hp": 40,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "upgraded_cards": [
              "CARD.FLICK_FLACK"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_transformed": [
              {
                "final_card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.FLECHETTES"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_SILENT"
                }
              },
              {
                "final_card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 14,
                  "id": "CARD.KNIFE_TRAP"
                },
                "original_card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.STRIKE_SILENT"
                }
              }
            ],
            "current_gold": 0,
            "current_hp": 40,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "MORPHIC_GROVE.pages.INITIAL.options.GROUP.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 171,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.MORPHIC_GROVE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 15,
                  "id": "CARD.UNTOUCHABLE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SPEEDSTER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PREDATOR"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.UNTOUCHABLE"
              }
            ],
            "current_gold": 31,
            "current_hp": 13,
            "damage_taken": 27,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.OROBIC_ACID",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.POISON_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BAG_OF_MARBLES",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BYGONE_EFFIGY_ELITE",
            "monster_ids": [
              "MONSTER.BYGONE_EFFIGY"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 31,
            "current_hp": 34,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 21,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 17,
                  "id": "CARD.FAN_OF_KNIVES"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ASSASSINATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SHADOW_STEP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.FAN_OF_KNIVES"
              }
            ],
            "current_gold": 106,
            "current_hp": 32,
            "damage_taken": 2,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.OROBIC_ACID"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_KIN_BOSS",
            "monster_ids": [
              "MONSTER.KIN_FOLLOWER",
              "MONSTER.KIN_FOLLOWER",
              "MONSTER.KIN_PRIEST"
            ],
            "room_type": "boss",
            "turns_taken": 10
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "PAELS_FLESH",
                "title": {
                  "key": "PAELS_FLESH.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "PAELS_CLAW",
                "title": {
                  "key": "PAELS_CLAW.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PAELS_EYE",
                "title": {
                  "key": "PAELS_EYE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 106,
            "current_hp": 62,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "PAELS_FLESH.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 30,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.PAELS_FLESH",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.PAEL",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 19,
                  "id": "CARD.TACTICIAN"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FOLLOW_THROUGH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CLOAK_AND_DAGGER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.TACTICIAN"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 9,
                "id": "CARD.PINPOINT"
              }
            ],
            "current_gold": 106,
            "current_hp": 36,
            "damage_taken": 26,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.CLARITY",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THIEVING_HOPPER_WEAK",
            "monster_ids": [
              "MONSTER.THIEVING_HOPPER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.BACKSTAB"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FLICK_FLACK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SNAKEBITE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CALCULATED_GAMBLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FOOTWORK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SPLASH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MAYHEM"
                },
                "was_picked": false
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_SILENT"
              }
            ],
            "current_gold": 6,
            "current_hp": 36,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 100,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.HEART_OF_IRON",
                "was_picked": false
              },
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PETRIFIED_TOAD",
                "was_picked": false
              },
              {
                "choice": "RELIC.HORN_CLEAT",
                "was_picked": false
              },
              {
                "choice": "RELIC.KIFUDA",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 21,
                  "id": "CARD.CALCULATED_GAMBLE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.FLICK_FLACK"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.CALCULATED_GAMBLE"
              }
            ],
            "current_gold": 21,
            "current_hp": 36,
            "damage_taken": 0,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.GIGANTIFICATION_POTION",
                "was_picked": true
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BOWLBUGS_WEAK",
            "monster_ids": [
              "MONSTER.BOWLBUG_ROCK",
              "MONSTER.BOWLBUG_EGG"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 22,
                  "id": "CARD.DEFLECT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DEADLY_POISON"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PRECISE_CUT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.DEFLECT"
              }
            ],
            "current_gold": 36,
            "current_hp": 36,
            "damage_taken": 0,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.STABLE_SERUM",
                "was_picked": false
              }
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.MYTES_NORMAL",
            "monster_ids": [
              "MONSTER.MYTE",
              "MONSTER.MYTE"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 23,
                  "id": "CARD.DODGE_AND_ROLL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FLICK_FLACK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.DODGE_AND_ROLL"
              }
            ],
            "current_gold": 46,
            "current_hp": 11,
            "damage_taken": 25,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.CLARITY"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.LOUSE_PROGENITOR_NORMAL",
            "monster_ids": [
              "MONSTER.LOUSE_PROGENITOR"
            ],
            "room_type": "monster",
            "turns_taken": 8
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "current_gold": 46,
            "current_hp": 0,
            "damage_taken": 11,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 70,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.GIGANTIFICATION_POTION"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DECIMILLIPEDE_ELITE",
            "monster_ids": [
              "MONSTER.DECIMILLIPEDE_SEGMENT_FRONT",
              "MONSTER.DECIMILLIPEDE_SEGMENT_MIDDLE",
              "MONSTER.DECIMILLIPEDE_SEGMENT_BACK"
            ],
            "room_type": "elite",
            "turns_taken": 2
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "badges": [],
      "character": "CHARACTER.SILENT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_SILENT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.NEUTRALIZE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.SURVIVOR"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.LEADING_STRIKE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ANTICIPATE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.SKEWER"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.ACROBATICS"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.FOLLOW_THROUGH"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.DEFLECT"
        },
        {
          "floor_added_to_deck": 6,
          "id": "CARD.PREPARED"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 6,
          "id": "CARD.FLICK_FLACK"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 12,
          "id": "CARD.PIERCING_WAIL"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.FLECHETTES"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 14,
          "id": "CARD.KNIFE_TRAP"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 15,
          "id": "CARD.UNTOUCHABLE"
        },
        {
          "floor_added_to_deck": 17,
          "id": "CARD.FAN_OF_KNIVES"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 19,
          "id": "CARD.TACTICIAN"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 21,
          "id": "CARD.CALCULATED_GAMBLE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 22,
          "id": "CARD.DEFLECT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 23,
          "id": "CARD.DODGE_AND_ROLL"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.RING_OF_THE_SNAKE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.SCROLL_BOXES"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.BRONZE_SCALES"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.TOXIC_EGG"
        },
        {
          "floor_added_to_deck": 15,
          "id": "RELIC.BAG_OF_MARBLES"
        },
        {
          "floor_added_to_deck": 18,
          "id": "RELIC.PAELS_FLESH"
        }
      ]
    }
  ],
  "run_time": 1123,
  "schema_version": 9,
  "seed": "6XW29J1SC4",
  "start_time": 1777698192,
  "was_abandoned": false,
  "win": false
}